export const BANNER_LIST_REQUEST = "BANNER_LIST_REQUEST";
export const BANNER_LIST_SUCCESS = "BANNER_LIST_SUCCESS";
export const BANNER_LIST_FAIL = "BANNER_LIST_FAIL";

export const BANNER_DETAILS_REQUEST = "BANNER_DETAILS_REQUEST";
export const BANNER_DETAILS_SUCCESS = "BANNER_DETAILS_SUCCESS";
export const BANNER_DETAILS_FAIL = "BANNER_DETAILS_FAIL";

export const BANNER_MODIFICATION_REQUEST = "BANNER_MODIFICATION_REQUEST";
export const BANNER_MODIFICATION_SUCCESS = "BANNER_MODIFICATION_SUCCESS";
export const BANNER_MODIFICATION_FAIL = "BANNER_MODIFICATION_FAIL";

export const BANNER_CREATE_REQUEST = "BANNER_CREATE_REQUEST";
export const BANNER_CREATE_SUCCESS = "BANNER_CREATE_SUCCESS";
export const BANNER_CREATE_FAIL = "BANNER_CREATE_FAIL";
export const BANNER_CREATE_RESET = "BANNER_CREATE_RESET";

export const BANNER_UPDATE_REQUEST = "BANNER_UPDATE_REQUEST";
export const BANNER_UPDATE_SUCCESS = "BANNER_UPDATE_SUCCESS";
export const BANNER_UPDATE_FAIL = "BANNER_UPDATE_FAIL";
export const BANNER_UPDATE_RESET = "BANNER_UPDATE_RESET";

export const BANNER_DELETE_REQUEST = "BANNER_DELETE_REQUEST";
export const BANNER_DELETE_SUCCESS = "BANNER_DELETE_SUCCESS";
export const BANNER_DELETE_FAIL = "BANNER_DELETE_FAIL";
export const BANNER_DELETE_RESET = "BANNER_DELETE_RESET";
