export const GENERAL_LIST_REQUEST = "GENERAL_LIST_REQUEST";
export const GENERAL_LIST_SUCCESS = "GENERAL_LIST_SUCCESS";
export const GENERAL_LIST_FAIL = "GENERAL_LIST_FAIL";

export const DASHBOARD_LIST_REQUEST = "DASHBOARD_LIST_REQUEST";
export const DASHBOARD_LIST_SUCCESS = "DASHBOARD_LIST_SUCCESS";
export const DASHBOARD_LIST_FAIL = "DASHBOARD_LIST_FAIL";

export const AFFILIATESTAT_CREATE_REQUEST = "AFFILIATESTAT_CREATE_REQUEST";
export const AFFILIATESTAT_CREATE_SUCCESS = "AFFILIATESTAT_CREATE_SUCCESS";
export const AFFILIATESTAT_CREATE_FAIL = "AFFILIATESTAT_CREATE_FAIL";
export const AFFILIATESTAT_CREATE_RESET = "AFFILIATESTAT_CREATE_RESET";

export const PRODUCTSTAT_CREATE_REQUEST = "PRODUCTSTAT_CREATE_REQUEST";
export const PRODUCTSTAT_CREATE_SUCCESS = "PRODUCTSTAT_CREATE_SUCCESS";
export const PRODUCTSTAT_CREATE_FAIL = "PRODUCTSTAT_CREATE_FAIL";
export const PRODUCTSTAT_CREATE_RESET = "PRODUCTSTAT_CREATE_RESET";

export const OVERALL_CREATE_REQUEST = "OVERALL_CREATE_REQUEST";
export const OVERALL_CREATE_SUCCESS = "OVERALL_CREATE_SUCCESS";
export const OVERALL_CREATE_FAIL = "OVERALL_CREATE_FAIL";
export const OVERALL_CREATE_RESET = "OVERALL_CREATE_RESET";
