export const PARTENAIRE_LIST_REQUEST = "PARTENAIRE_LIST_REQUEST";
export const PARTENAIRE_LIST_SUCCESS = "PARTENAIRE_LIST_SUCCESS";
export const PARTENAIRE_LIST_FAIL = "PARTENAIRE_LIST_FAIL";

export const MARQUE_LIST_REQUEST = "MARQUE_LIST_REQUEST";
export const MARQUE_LIST_SUCCESS = "MARQUE_LIST_SUCCESS";
export const MARQUE_LIST_FAIL = "MARQUE_LIST_FAIL";

export const TROPHE_LIST_REQUEST = "TROPHE_LIST_REQUEST";
export const TROPHE_LIST_SUCCESS = "TROPHE_LIST_SUCCESS";
export const TROPHE_LIST_FAIL = "TROPHE_LIST_FAIL";
