export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUITS_LIST_REQUEST = "PRODUITS_LIST_REQUEST";
export const PRODUITS_LIST_SUCCESS = "PRODUITS_LIST_SUCCESS";
export const PRODUITS_LIST_FAIL = "PRODUITS_LIST_FAIL";

export const PRODUITS_LIST_RECENTS_REQUEST = "PRODUITS_LIST_RECENTS_REQUEST";
export const PRODUITS_LIST_RECENTS_SUCCESS = "PRODUITS_LIST_RECENTS_SUCCESS";
export const PRODUITS_LIST_RECENTS_FAIL = "PRODUITS_LIST_RECENTS_FAIL";

export const PRODUITS_LIST_STAT_REQUEST = "PRODUITS_LIST_STAT_REQUEST";
export const PRODUITS_LIST_STAT_SUCCESS = "PRODUITS_LIST_STAT_SUCCESS";
export const PRODUITS_LIST_STAT_FAIL = "PRODUITS_LIST_STAT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_REVIEW_CREATE_REQUEST = "PRODUCT_REVIEW_CREATE_REQUEST";
export const PRODUCT_REVIEW_CREATE_SUCCESS = "PRODUCT_REVIEW_CREATE_SUCCESS";
export const PRODUCT_REVIEW_CREATE_FAIL = "PRODUCT_REVIEW_CREATE_FAIL";
export const PRODUCT_REVIEW_CREATE_RESET = "PRODUCT_REVIEW_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";

export const PRODUCT_UPDATE_IMAGES = "PRODUCT_UPDATE_IMAGES";
export const PRODUCT_DELETE_IMAGES = "PRODUCT_DELETE_IMAGES";
export const PRODUCT_UPDATE_ADDED_IMAGES = "PRODUCT_UPDATE_ADDED_IMAGES";
export const PRODUCT_UPDATE_DELETED_IMAGES = "PRODUCT_UPDATE_DELETED_IMAGES";
export const PRODUCT_UPLOAD_IMAGES_REQUEST = "PRODUCT_UPLOAD_IMAGES_REQUEST";
