export const WISHLIST_ADD_ITEM_FAIL = "WISHLIST_ADD_ITEM_FAIL";
export const WISHLIST_ADD_ITEM = "WISHLIST_ADD_ITEM";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
export const WISHLIST_EMPTY = "WISHLIST_EMPTY";
