export const APITHERAPIE_LIST_REQUEST = "APITHERAPIE_LIST_REQUEST";
export const APITHERAPIE_LIST_SUCCESS = "APITHERAPIE_LIST_SUCCESS";
export const APITHERAPIE_LIST_FAIL = "APITHERAPIE_LIST_FAIL";

export const APITHERAPIE_LIST_POPULAIRE_REQUEST =
  "APITHERAPIE_LIST_POPULAIRE_REQUEST";
export const APITHERAPIE_LIST_POPULAIRE_SUCCESS =
  "APITHERAPIE_LIST_POPULAIRE_SUCCESS";
export const APITHERAPIE_LIST_POPULAIRE_FAIL =
  "APITHERAPIE_LIST_POPULAIRE_FAIL";

export const APITHERAPIE_LIST_SEARCH_REQUEST =
  "APITHERAPIE_LIST_SEARCH_REQUEST";
export const APITHERAPIE_LIST_SEARCH_SUCCESS =
  "APITHERAPIE_LIST_SEARCH_SUCCESS";
export const APITHERAPIE_LIST_SEARCH_FAIL = "APITHERAPIE_LIST_SEARCH_FAIL";

export const APITHERAPIE_DETAILS_REQUEST = "APITHERAPIE_DETAILS_REQUEST";
export const APITHERAPIE_DETAILS_SUCCESS = "APITHERAPIE_DETAILS_SUCCESS";
export const APITHERAPIE_DETAILS_FAIL = "APITHERAPIE_DETAILS_FAIL";

export const APITHERAPIE_MODIFICATION_REQUEST =
  "APITHERAPIE_MODIFICATION_REQUEST";
export const APITHERAPIE_MODIFICATION_SUCCESS =
  "APITHERAPIE_MODIFICATION_SUCCESS";
export const APITHERAPIE_MODIFICATION_FAIL = "APITHERAPIE_MODIFICATION_FAIL";

export const APITHERAPIE_CREATE_REQUEST = "APITHERAPIE_CREATE_REQUEST";
export const APITHERAPIE_CREATE_SUCCESS = "APITHERAPIE_CREATE_SUCCESS";
export const APITHERAPIE_CREATE_FAIL = "APITHERAPIE_CREATE_FAIL";
export const APITHERAPIE_CREATE_RESET = "APITHERAPIE_CREATE_RESET";

export const APITHERAPIE_REVIEW_CREATE_REQUEST =
  "APITHERAPIE_REVIEW_CREATE_REQUEST";
export const APITHERAPIE_REVIEW_CREATE_SUCCESS =
  "APITHERAPIE_REVIEW_CREATE_SUCCESS";
export const APITHERAPIE_REVIEW_CREATE_FAIL = "APITHERAPIE_REVIEW_CREATE_FAIL";
export const APITHERAPIE_REVIEW_CREATE_RESET =
  "APITHERAPIE_REVIEW_CREATE_RESET";

export const APITHERAPIE_UPDATE_REQUEST = "APITHERAPIE_UPDATE_REQUEST";
export const APITHERAPIE_UPDATE_SUCCESS = "APITHERAPIE_UPDATE_SUCCESS";
export const APITHERAPIE_UPDATE_FAIL = "APITHERAPIE_UPDATE_FAIL";
export const APITHERAPIE_UPDATE_RESET = "APITHERAPIE_UPDATE_RESET";

export const APITHERAPIE_DELETE_REQUEST = "APITHERAPIE_DELETE_REQUEST";
export const APITHERAPIE_DELETE_SUCCESS = "APITHERAPIE_DELETE_SUCCESS";
export const APITHERAPIE_DELETE_FAIL = "APITHERAPIE_DELETE_FAIL";
export const APITHERAPIE_DELETE_RESET = "APITHERAPIE_DELETE_RESET";

export const APITHERAPIE_CATEGORY_LIST_REQUEST =
  "APITHERAPIE_CATEGORY_LIST_REQUEST";
export const APITHERAPIE_CATEGORY_LIST_SUCCESS =
  "APITHERAPIE_CATEGORY_LIST_SUCCESS";
export const APITHERAPIE_CATEGORY_LIST_FAIL = "APITHERAPIE_CATEGORY_LIST_FAIL";
