export const GALERIE_LIST_REQUEST = "GALERIE_LIST_REQUEST";
export const GALERIE_LIST_SUCCESS = "GALERIE_LIST_SUCCESS";
export const GALERIE_LIST_FAIL = "GALERIE_LIST_FAIL";

export const GALERIE_DETAILS_REQUEST = "GALERIE_DETAILS_REQUEST";
export const GALERIE_DETAILS_SUCCESS = "GALERIE_DETAILS_SUCCESS";
export const GALERIE_DETAILS_FAIL = "GALERIE_DETAILS_FAIL";

export const GALERIE_CREATE_REQUEST = "GALERIE_CREATE_REQUEST";
export const GALERIE_CREATE_SUCCESS = "GALERIE_CREATE_SUCCESS";
export const GALERIE_CREATE_FAIL = "GALERIE_CREATE_FAIL";
export const GALERIE_CREATE_RESET = "GALERIE_CREATE_RESET";

export const GALERIE_UPDATE_REQUEST = "GALERIE_UPDATE_REQUEST";
export const GALERIE_UPDATE_SUCCESS = "GALERIE_UPDATE_SUCCESS";
export const GALERIE_UPDATE_FAIL = "GALERIE_UPDATE_FAIL";
export const GALERIE_UPDATE_RESET = "GALERIE_UPDATE_RESET";

export const GALERIE_DELETE_REQUEST = "GALERIE_DELETE_REQUEST";
export const GALERIE_DELETE_SUCCESS = "GALERIE_DELETE_SUCCESS";
export const GALERIE_DELETE_FAIL = "GALERIE_DELETE_FAIL";
export const GALERIE_DELETE_RESET = "GALERIE_DELETE_RESET";
