export const HERO_LIST_REQUEST = "HERO_LIST_REQUEST";
export const HERO_LIST_SUCCESS = "HERO_LIST_SUCCESS";
export const HERO_LIST_FAIL = "HERO_LIST_FAIL";

export const HERO_LIST_POPULAIRE_REQUEST = "HERO_LIST_POPULAIRE_REQUEST";
export const HERO_LIST_POPULAIRE_SUCCESS = "HERO_LIST_POPULAIRE_SUCCESS";
export const HERO_LIST_POPULAIRE_FAIL = "HERO_LIST_POPULAIRE_FAIL";

export const HERO_LIST_SEARCH_REQUEST = "HERO_LIST_SEARCH_REQUEST";
export const HERO_LIST_SEARCH_SUCCESS = "HERO_LIST_SEARCH_SUCCESS";
export const HERO_LIST_SEARCH_FAIL = "HERO_LIST_SEARCH_FAIL";

export const HERO_DETAILS_REQUEST = "HERO_DETAILS_REQUEST";
export const HERO_DETAILS_SUCCESS = "HERO_DETAILS_SUCCESS";
export const HERO_DETAILS_FAIL = "HERO_DETAILS_FAIL";

export const HERO_MODIFICATION_REQUEST = "HERO_MODIFICATION_REQUEST";
export const HERO_MODIFICATION_SUCCESS = "HERO_MODIFICATION_SUCCESS";
export const HERO_MODIFICATION_FAIL = "HERO_MODIFICATION_FAIL";

export const HERO_CREATE_REQUEST = "HERO_CREATE_REQUEST";
export const HERO_CREATE_SUCCESS = "HERO_CREATE_SUCCESS";
export const HERO_CREATE_FAIL = "HERO_CREATE_FAIL";
export const HERO_CREATE_RESET = "HERO_CREATE_RESET";

export const HERO_REVIEW_CREATE_REQUEST = "HERO_REVIEW_CREATE_REQUEST";
export const HERO_REVIEW_CREATE_SUCCESS = "HERO_REVIEW_CREATE_SUCCESS";
export const HERO_REVIEW_CREATE_FAIL = "HERO_REVIEW_CREATE_FAIL";
export const HERO_REVIEW_CREATE_RESET = "HERO_REVIEW_CREATE_RESET";

export const HERO_UPDATE_REQUEST = "HERO_UPDATE_REQUEST";
export const HERO_UPDATE_SUCCESS = "HERO_UPDATE_SUCCESS";
export const HERO_UPDATE_FAIL = "HERO_UPDATE_FAIL";
export const HERO_UPDATE_RESET = "HERO_UPDATE_RESET";

export const HERO_DELETE_REQUEST = "HERO_DELETE_REQUEST";
export const HERO_DELETE_SUCCESS = "HERO_DELETE_SUCCESS";
export const HERO_DELETE_FAIL = "HERO_DELETE_FAIL";
export const HERO_DELETE_RESET = "HERO_DELETE_RESET";

export const HERO_CATEGORY_LIST_REQUEST = "HERO_CATEGORY_LIST_REQUEST";
export const HERO_CATEGORY_LIST_SUCCESS = "HERO_CATEGORY_LIST_SUCCESS";
export const HERO_CATEGORY_LIST_FAIL = "HERO_CATEGORY_LIST_FAIL";
