export const LIFESTYLE_LIST_REQUEST = "LIFESTYLE_LIST_REQUEST";
export const LIFESTYLE_LIST_SUCCESS = "LIFESTYLE_LIST_SUCCESS";
export const LIFESTYLE_LIST_FAIL = "LIFESTYLE_LIST_FAIL";

export const LIFESTYLE_LIST_POPULAIRE_REQUEST =
  "LIFESTYLE_LIST_POPULAIRE_REQUEST";
export const LIFESTYLE_LIST_POPULAIRE_SUCCESS =
  "LIFESTYLE_LIST_POPULAIRE_SUCCESS";
export const LIFESTYLE_LIST_POPULAIRE_FAIL = "LIFESTYLE_LIST_POPULAIRE_FAIL";

export const LIFESTYLE_DETAILS_REQUEST = "LIFESTYLE_DETAILS_REQUEST";
export const LIFESTYLE_DETAILS_SUCCESS = "LIFESTYLE_DETAILS_SUCCESS";
export const LIFESTYLE_DETAILS_FAIL = "LIFESTYLE_DETAILS_FAIL";

export const LIFESTYLE_MODIFICATION_REQUEST = "LIFESTYLE_MODIFICATION_REQUEST";
export const LIFESTYLE_MODIFICATION_SUCCESS = "LIFESTYLE_MODIFICATION_SUCCESS";
export const LIFESTYLE_MODIFICATION_FAIL = "LIFESTYLE_MODIFICATION_FAIL";

export const LIFESTYLE_CREATE_REQUEST = "LIFESTYLE_CREATE_REQUEST";
export const LIFESTYLE_CREATE_SUCCESS = "LIFESTYLE_CREATE_SUCCESS";
export const LIFESTYLE_CREATE_FAIL = "LIFESTYLE_CREATE_FAIL";
export const LIFESTYLE_CREATE_RESET = "LIFESTYLE_CREATE_RESET";

export const LIFESTYLE_REVIEW_CREATE_REQUEST =
  "LIFESTYLE_REVIEW_CREATE_REQUEST";
export const LIFESTYLE_REVIEW_CREATE_SUCCESS =
  "LIFESTYLE_REVIEW_CREATE_SUCCESS";
export const LIFESTYLE_REVIEW_CREATE_FAIL = "LIFESTYLE_REVIEW_CREATE_FAIL";
export const LIFESTYLE_REVIEW_CREATE_RESET = "LIFESTYLE_REVIEW_CREATE_RESET";

export const LIFESTYLE_UPDATE_REQUEST = "LIFESTYLE_UPDATE_REQUEST";
export const LIFESTYLE_UPDATE_SUCCESS = "LIFESTYLE_UPDATE_SUCCESS";
export const LIFESTYLE_UPDATE_FAIL = "LIFESTYLE_UPDATE_FAIL";
export const LIFESTYLE_UPDATE_RESET = "LIFESTYLE_UPDATE_RESET";

export const LIFESTYLE_DELETE_REQUEST = "LIFESTYLE_DELETE_REQUEST";
export const LIFESTYLE_DELETE_SUCCESS = "LIFESTYLE_DELETE_SUCCESS";
export const LIFESTYLE_DELETE_FAIL = "LIFESTYLE_DELETE_FAIL";
export const LIFESTYLE_DELETE_RESET = "LIFESTYLE_DELETE_RESET";

export const LIFESTYLE_CATEGORY_LIST_REQUEST =
  "LIFESTYLE_CATEGORY_LIST_REQUEST";
export const LIFESTYLE_CATEGORY_LIST_SUCCESS =
  "LIFESTYLE_CATEGORY_LIST_SUCCESS";
export const LIFESTYLE_CATEGORY_LIST_FAIL = "LIFESTYLE_CATEGORY_LIST_FAIL";
