export const POPULAIRE_LIST_REQUEST = "POPULAIRE_LIST_REQUEST";
export const POPULAIRE_LIST_SUCCESS = "POPULAIRE_LIST_SUCCESS";
export const POPULAIRE_LIST_FAIL = "POPULAIRE_LIST_FAIL";

export const POPULAIRE_LIST_SEARCH_REQUEST = "POPULAIRE_LIST_SEARCH_REQUEST";
export const POPULAIRE_LIST_SEARCH_SUCCESS = "POPULAIRE_LIST_SEARCH_SUCCESS";
export const POPULAIRE_LIST_SEARCH_FAIL = "POPULAIRE_LIST_SEARCH_FAIL";

export const POPULAIRE_DETAILS_REQUEST = "POPULAIRE_DETAILS_REQUEST";
export const POPULAIRE_DETAILS_SUCCESS = "POPULAIRE_DETAILS_SUCCESS";
export const POPULAIRE_DETAILS_FAIL = "POPULAIRE_DETAILS_FAIL";

export const POPULAIRE_MODIFICATION_REQUEST = "POPULAIRE_MODIFICATION_REQUEST";
export const POPULAIRE_MODIFICATION_SUCCESS = "POPULAIRE_MODIFICATION_SUCCESS";
export const POPULAIRE_MODIFICATION_FAIL = "POPULAIRE_MODIFICATION_FAIL";

export const POPULAIRE_CREATE_REQUEST = "POPULAIRE_CREATE_REQUEST";
export const POPULAIRE_CREATE_SUCCESS = "POPULAIRE_CREATE_SUCCESS";
export const POPULAIRE_CREATE_FAIL = "POPULAIRE_CREATE_FAIL";
export const POPULAIRE_CREATE_RESET = "POPULAIRE_CREATE_RESET";

export const POPULAIRE_REVIEW_CREATE_REQUEST =
  "POPULAIRE_REVIEW_CREATE_REQUEST";
export const POPULAIRE_REVIEW_CREATE_SUCCESS =
  "POPULAIRE_REVIEW_CREATE_SUCCESS";
export const POPULAIRE_REVIEW_CREATE_FAIL = "POPULAIRE_REVIEW_CREATE_FAIL";
export const POPULAIRE_REVIEW_CREATE_RESET = "POPULAIRE_REVIEW_CREATE_RESET";

export const POPULAIRE_UPDATE_REQUEST = "POPULAIRE_UPDATE_REQUEST";
export const POPULAIRE_UPDATE_SUCCESS = "POPULAIRE_UPDATE_SUCCESS";
export const POPULAIRE_UPDATE_FAIL = "POPULAIRE_UPDATE_FAIL";
export const POPULAIRE_UPDATE_RESET = "POPULAIRE_UPDATE_RESET";

export const POPULAIRE_DELETE_REQUEST = "POPULAIRE_DELETE_REQUEST";
export const POPULAIRE_DELETE_SUCCESS = "POPULAIRE_DELETE_SUCCESS";
export const POPULAIRE_DELETE_FAIL = "POPULAIRE_DELETE_FAIL";
export const POPULAIRE_DELETE_RESET = "POPULAIRE_DELETE_RESET";

export const POPULAIRE_CATEGORY_LIST_REQUEST =
  "POPULAIRE_CATEGORY_LIST_REQUEST";
export const POPULAIRE_CATEGORY_LIST_SUCCESS =
  "POPULAIRE_CATEGORY_LIST_SUCCESS";
export const POPULAIRE_CATEGORY_LIST_FAIL = "POPULAIRE_CATEGORY_LIST_FAIL";
