export const TIKTOK_LIST_REQUEST = "TIKTOK_LIST_REQUEST";
export const TIKTOK_LIST_SUCCESS = "TIKTOK_LIST_SUCCESS";
export const TIKTOK_LIST_FAIL = "TIKTOK_LIST_FAIL";

export const TIKTOK_DETAILS_REQUEST = "TIKTOK_DETAILS_REQUEST";
export const TIKTOK_DETAILS_SUCCESS = "TIKTOK_DETAILS_SUCCESS";
export const TIKTOK_DETAILS_FAIL = "TIKTOK_DETAILS_FAIL";

export const TIKTOK_MODIFICATION_REQUEST = "TIKTOK_MODIFICATION_REQUEST";
export const TIKTOK_MODIFICATION_SUCCESS = "TIKTOK_MODIFICATION_SUCCESS";
export const TIKTOK_MODIFICATION_FAIL = "TIKTOK_MODIFICATION_FAIL";

export const TIKTOK_CREATE_REQUEST = "TIKTOK_CREATE_REQUEST";
export const TIKTOK_CREATE_SUCCESS = "TIKTOK_CREATE_SUCCESS";
export const TIKTOK_CREATE_FAIL = "TIKTOK_CREATE_FAIL";
export const TIKTOK_CREATE_RESET = "TIKTOK_CREATE_RESET";

export const TIKTOK_UPDATE_REQUEST = "TIKTOK_UPDATE_REQUEST";
export const TIKTOK_UPDATE_SUCCESS = "TIKTOK_UPDATE_SUCCESS";
export const TIKTOK_UPDATE_FAIL = "TIKTOK_UPDATE_FAIL";
export const TIKTOK_UPDATE_RESET = "TIKTOK_UPDATE_RESET";

export const TIKTOK_DELETE_REQUEST = "TIKTOK_DELETE_REQUEST";
export const TIKTOK_DELETE_SUCCESS = "TIKTOK_DELETE_SUCCESS";
export const TIKTOK_DELETE_FAIL = "TIKTOK_DELETE_FAIL";
export const TIKTOK_DELETE_RESET = "TIKTOK_DELETE_RESET";
